apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: iot-demo
  namespace: demo
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel