apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: route-demo
  namespace: default
spec:
  traffic:
  - configurationName: blue-config
    percent: 0
    name: v1
  - configurationName: green-config
    percent: 100