apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: route-demo
  namespace: default
spec:
  traffic:
  - configurationName: revision0-config
    percent: 50
  - configurationName: revision1-config
    percent: 50
    name: v2