apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: vision
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/mchmarny/spring-cloud-gcp.git
            revision: s1p-demo
        template:
          name: jib-maven
          arguments:
          - name: DIRECTORY
            value: spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample
          - name: IMAGE
            value: &image us.gcr.io/s9-demo/vision:1.6.2
          - name: CACHE
            value: persistent-cache
        volumes:
        - name: persistent-cache
          persistentVolumeClaim:
            claimName: jib-build-cache
      revisionTemplate:
        spec:
          container:
            image: *image
