apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: APP_NAME
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/APP_NAME:TAG_REF
          env:
            - name: RELEASE
              value: "TAG_REF"
