#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# eventing
kubectl apply \
-f https://storage.googleapis.com/knative-nightly/eventing/latest/eventing.yaml

# eventing GCP
kubectl apply \
-f https://storage.googleapis.com/knative-nightly/eventing/latest/in-memory-channel.yaml
-f https://storage.googleapis.com/knative-nightly/knative-gcp/latest/cloud-run-events.yaml

# create demo namespace and label for eventing brokers
kubectl create ns $DEMO_NAMESPACE
kubectl label namespace $DEMO_NAMESPACE knative-eventing-injection=enabled

# watch until all good eventing
watch kubectl get pods -n knative-eventing
