#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# GPU POOL
# gcloud compute accelerator-types list
gcloud container node-pools create gpu-node-pool \
  --zone $CLUSTER_ZONE --cluster $CLUSTER_NAME \
  --machine-type=n1-standard-4 \
  --accelerator type=nvidia-tesla-p100,count=1 \
  --num-nodes 1 --min-nodes 1 --max-nodes 1 \
  --enable-autoscaling

# GPU Drivers
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/ubuntu/daemonset-preloaded.yaml
