apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scale
  namespace: demo
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: gcr.io/cloudylabs-public/maxprime:0.2.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: RELEASE
              value: "v0.2.1-scale"
