apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: jib-maven-vision-image-build
spec:
  serviceAccount: build-bot
  taskRef:
    name: jib-maven
  podTemplate:
    volumes:
      - name: jib-build-cache
        persistentVolumeClaim:
          claimName: jib-build-cache
  inputs:
    resources:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/mchmarny/spring-cloud-gcp
            - name: revision
              value: s1p-demo
    params:
      - name: DIRECTORY
        value: ./spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample
      - name: CACHE
        value: jib-build-cache
  outputs:
    resources:
      - name: image
        resourceSpec:
          type: image
          params:
            - name: url
              value: gcr.io/cloudylabs/vision:3.2.13
