apiVersion: v1
kind: Secret
metadata:
  name: build-secret
  annotations:
    build.knative.dev/docker-0: https://us.gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: _json_key
  password: