#!/bin/bash

# Meta
export PROJECT_ID="s9-demo"
export CLUSTER_NAME="kn03"
export CLUSTER_REGION="us-west1"
export CLUSTER_ZONE="${CLUSTER_REGION}-c"
export START_CLUSTER_NODE_SIZE=3
export MAX_CLUSTER_NODE_SIZE=10

# Domain
export CLUSTER_DOMAIN="knative.tech"
# gcloud beta compute addresses create "${CLUSTER_NAME}-ip" --region=$CLUSTER_REGION
# gcloud beta compute addresses list
export STATIC_IP="35.199.160.136" 

# Certs
# certbot certonly --manual --preferred-challenges dns -d '*.default.knative.tech'
export TLS_CERT_PATH="/Users/mchmarny/.gcp-keys/knative.tech/ca.pem"
export TLS_KEY_PATH="/Users/mchmarny/.gcp-keys/knative.tech/pk.pem"

# API
gcloud services enable \
  cloudapis.googleapis.com \
  container.googleapis.com \
  containerregistry.googleapis.com

# Cluster
# gcloud container clusters delete $CLUSTER_NAME
gcloud container clusters create $CLUSTER_NAME \
  --zone=$CLUSTER_ZONE \
  --cluster-version=latest \
  --machine-type=n1-standard-4 \
  --enable-autoscaling --min-nodes=1 --max-nodes=$MAX_CLUSTER_NODE_SIZE \
  --enable-autorepair \
  --scopes=cloud-platform,service-control,service-management,compute-rw,storage-ro,logging-write,monitoring-write,pubsub,datastore \
  --num-nodes=$START_CLUSTER_NODE_SIZE
  
# GPI
# https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
  --accelerator type=nvidia-tesla-v100

# Binding
kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole=cluster-admin \
--user=$(gcloud config get-value core/account)

# Istio
kubectl apply -f https://github.com/knative/serving/releases/download/v0.2.3/istio-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.2.3/istio.yaml
kubectl label namespace default istio-injection=enabled
kubectl get pods --namespace istio-system

# Knative
kubectl apply -f https://github.com/knative/serving/releases/download/v0.3.0/serving.yaml
kubectl apply -f https://github.com/knative/build/releases/download/v0.3.0/release.yaml
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.3.0/release.yaml
kubectl apply -f https://github.com/knative/eventing-sources/releases/download/v0.3.0/release.yaml

kubectl get pods --n knative-serving
kubectl get pods --n knative-build
kubectl get pods --n knative-eventing
kubectl get pods --n knative-sources
kubectl get pods --n knative-monitoring
kubectl get pods --n gcssource-system



# Static IP configured in ingress
kubectl patch svc knative-ingress-gateway --namespace istio-ingressgateway \
  -p "{\"spec\":{\"loadBalancerIP\":\"${STATIC_IP}\"}}"
kubectl get svc knative-ingressgateway --namespace istio-system -oyaml


# Outbound network
export NET_SCOPE=$(gcloud container clusters describe ${CLUSTER_NAME} --zone=${CLUSTER_ZONE} \
                  | grep -e clusterIpv4Cidr -e servicesIpv4Cidr \
                  | sed -e "s/clusterIpv4Cidr://" -e "s/servicesIpv4Cidr://" \
                  | xargs echo | sed -e "s/ /,/")
kubectl patch configmap config-network -n knative-serving -p \
    "{\"data\":{\"istio.sidecar.includeOutboundIPRanges\":\"${NET_SCOPE}\"}}"
kubectl get configmap config-network -n knative-serving -oyaml


# Custom domain
kubectl get configmap config-domain -n knative-serving -oyaml | \
  sed "s/example.com/${CLUSTER_DOMAIN}/" | \
  kubectl replace -f -


# Custom domain TLS
kubectl create -n istio-system secret tls istio-ingressgateway-certs \
  --key $TLS_KEY_PATH --cert $TLS_CERT_PATH

# Gateway
kubectl apply -f https://raw.githubusercontent.com/mchmarny/knative-demos/master/scripts/tls-gateway-patch.yaml

