#!/bin/bash

export PROJECT_ID="marek-demo"
export CLUSTER_NAME="knative"
export CLUSTER_REGION="us-west1"
export CLUSTER_ZONE="${CLUSTER_REGION}-c"
export CLUSTER_DOMAIN="knative.tech"
# gcloud beta compute addresses create knative-v022-ip --region=us-west1
export STATIC_IP="35.197.82.104" # gcloud beta compute addresses list
export START_CLUSTER_NODE_SIZE=3
export MAX_CLUSTER_NODE_SIZE=10
# certbot certonly --manual --preferred-challenges dns -d '*.default.knative.tech'
export TLS_CERT_PATH="/Users/mchmarny/.gcp-keys/knative.tech/ca.pem"
export TLS_KEY_PATH="/Users/mchmarny/.gcp-keys/knative.tech/pk.pem"
# export SA_KEY_PATH="/home/mchmarny/knative/certs/build-sa.json" # edit in sa.yaml

# API
gcloud services enable \
  cloudapis.googleapis.com \
  container.googleapis.com \
  containerregistry.googleapis.com

# Cluster
# gcloud container clusters delete $CLUSTER_NAME
gcloud container clusters create $CLUSTER_NAME \
  --zone=$CLUSTER_ZONE \
  --cluster-version=latest \
  --machine-type=n1-standard-4 \
  --enable-autoscaling --min-nodes=1 --max-nodes=$MAX_CLUSTER_NODE_SIZE \
  --enable-autorepair \
  --scopes=cloud-platform,service-control,service-management,compute-rw,storage-ro,logging-write,monitoring-write,pubsub,datastore \
  --num-nodes=$START_CLUSTER_NODE_SIZE

# Binding
kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole=cluster-admin \
--user=$(gcloud config get-value core/account)

# Istio
kubectl apply -f https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml
kubectl label namespace default istio-injection=enabled
watch kubectl get pods -n istio-system

# Knative
kubectl apply -f https://storage.googleapis.com/knative-releases/serving/latest/release.yaml
watch kubectl get pods -n knative-serving

# Knative Build
kubectl apply -f https://raw.githubusercontent.com/knative/build-templates/master/kaniko/kaniko.yaml
kubectl apply -f https://raw.githubusercontent.com/knative/build-templates/master/jib/jib-maven.yaml
watch kubectl get pods -n knative-build

# Knative Events
kubectl apply -f https://storage.googleapis.com/knative-releases/eventing/latest/release.yaml


# Static IP configured in ingress
kubectl patch svc knative-ingressgateway --namespace istio-system \
  -p "{\"spec\":{\"loadBalancerIP\":\"${STATIC_IP}\"}}"
kubectl get svc knative-ingressgateway --namespace istio-system -oyaml


# Outbound network
export NET_SCOPE=$(gcloud container clusters describe ${CLUSTER_NAME} --zone=${CLUSTER_ZONE} \
                  | grep -e clusterIpv4Cidr -e servicesIpv4Cidr \
                  | sed -e "s/clusterIpv4Cidr://" -e "s/servicesIpv4Cidr://" \
                  | xargs echo | sed -e "s/ /,/")
kubectl patch configmap config-network -n knative-serving -p \
    "{\"data\":{\"istio.sidecar.includeOutboundIPRanges\":\"${NET_SCOPE}\"}}"
kubectl get configmap config-network -n knative-serving -oyaml


# Custom domain
kubectl get configmap config-domain -n knative-serving -oyaml | \
  sed "s/example.com/${CLUSTER_DOMAIN}/" | \
  kubectl replace -f -


# Custom domain TLS
kubectl create -n istio-system secret tls istio-ingressgateway-certs \
  --key $TLS_KEY_PATH --cert $TLS_CERT_PATH

# Gateway
kubectl apply -f tls-gateway-patch.yaml

# Seems like the follwoing steps are no longer required in 0.2.2
# Build secret and service account
# kubectl apply -f build-secret.yaml

# Add builder sa
# kubectl patch serviceaccount default -p "{\"secrets\":[{\"name\":\"build-secret\"}]}"
