#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# TODO: CloudRun add-on provisions older cluster
#       comment/uncomment cluster version specific things
#       in individual scripts


# API
gcloud services enable \
  cloudapis.googleapis.com \
  container.googleapis.com \
  containerregistry.googleapis.com

# Cluster
gcloud beta container clusters create $CLUSTER_NAME \
--addons=HorizontalPodAutoscaling,HttpLoadBalancing,Istio,CloudRun \
--machine-type $CLUSTER_NODE_MACHINE_TYPE \
--zone $CLUSTER_ZONE \
--enable-stackdriver-kubernetes \
--scopes cloud-platform

# credentials and binding
gcloud container clusters get-credentials $CLUSTER_NAME \
    --zone $CLUSTER_ZONE

kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)