#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

echo "currently reserved by not used IPs in ${CLUSTER_REGION} region:"
gcloud beta compute addresses list --filter="status:RESERVED AND region:${CLUSTER_REGION}"
read -p "Do want to create new IP? [Y/n]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "creating static IP: ${CLUSTER_NAME}-ip"
  gcloud beta compute addresses create "${CLUSTER_NAME}-ip" --region=$CLUSTER_REGION
  export EXTERNAL_IP=$(gcloud beta compute addresses describe ${CLUSTER_NAME}-ip --region=$CLUSTER_REGION --format="value(address)")
  echo "static IP ${CLUSTER_NAME}-ip: ${EXTERNAL_IP}"
  echo "setting ingress gateway to: ${EXTERNAL_IP}"
  kubectl patch svc istio-ingress -n gke-system \
    -p "{\"spec\":{\"loadBalancerIP\":\"${EXTERNAL_IP}\"}}"
  echo "ingress gateway set to: ${EXTERNAL_IP}. Current ingress:"
  kubectl get svc istio-ingress -n gke-system --output=json | jq ".status.loadBalancer.ingress[0].ip"
fi