#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# sudo certbot certonly --manual --preferred-challenges dns -d '*.demo.knative.tech'
# sudo cp /etc/letsencrypt/live/demo.knative.tech/fullchain.pem ./ca.pem
# sudo cp /etc/letsencrypt/live/demo.knative.tech/privkey.pem ./pk.pem
# sudo chmod 644 *.pem

# Custom domain TLS
# kubectl delete -n istio-system secret istio-ingressgateway-certs
kubectl create -n istio-system secret tls istio-ingressgateway-certs \
  --key $TLS_KEY_PATH --cert $TLS_CERT_PATH

# Gateway
kubectl apply -f gateway.yaml


