#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# sudo certbot certonly --manual --preferred-challenges dns -d '*.demo.cloudylabs.dev'
# sudo cp /etc/letsencrypt/live/demo.cloudylabs.dev/fullchain.pem ./ca.pem
# sudo cp /etc/letsencrypt/live/demo.cloudylabs.dev/privkey.pem ./pk.pem
# sudo chmod 644 *.pem

# Custom domain TLS
# kubectl delete -n gke-system secret istio-ingress-certs

kubectl create -n gke-system secret tls istio-ingress-certs \
  --key $TLS_KEY_PATH --cert $TLS_CERT_PATH

# Gateway
kubectl apply -f gateway.yaml


