#!/bin/bash

# cluster name
export CLUSTER_NAME="cr"

# cluster region
export CLUSTER_REGION="us-central1"

# cluster zone
export CLUSTER_ZONE="${CLUSTER_REGION}-a"

# initial cluster size
export CLUSTER_START_NODE_SIZE=3

# max cluster size
export CLUSTER_MAX_NODE_SIZE=10

# the type of VM used for worker nodes
export CLUSTER_NODE_MACHINE_TYPE="n2-standard-4"

# version of k8s
export CLUSTER_MASTER_VERSION="1.15.8-gke.2" # 1.15.8-gke.2

# knative
export KN_VERSION="v0.10.0"

# domain
# export CUSTOM_DOMAIN="knative.tech"
export CUSTOM_DOMAIN="cloudylabs.dev"

# static ip, leave empty to create
export CLUSTER_IP=""

# demo namespace, used for evneting broker injection
export DEMO_NAMESPACE="demo"

# certs
# to create new ones:
#    sudo certbot certonly --manual --preferred-challenges dns -d '*.demo.knative.tech'
#    sudo cp /etc/letsencrypt/live/demo.knative.tech/fullchain.pem ./ca.pem
#    sudo cp /etc/letsencrypt/live/demo.knative.tech/privkey.pem ./pk.pem
#    sudo chmod 644 *.pem
export TLS_CERT_PATH="/Users/mchmarny/.gcp-keys/${CUSTOM_DOMAIN}/ca.pem"
export TLS_KEY_PATH="/Users/mchmarny/.gcp-keys/${CUSTOM_DOMAIN}/pk.pem"

